### Transkribiere Audio mit dem tiny-Modell
POST http://127.0.0.1:8000/transcribe
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="audio.mp3"
Content-Type: audio/mpeg

< ./audio.mp3
--WebAppBoundary
Content-Disposition: form-data; name="model"

tiny
--WebAppBoundary--